language: r

sudo: false

dist: trusty

warnings_are_errors: false

Imports:
  - simts
  - wv

Remotes:
  - SMAC-Group/simts
  - SMAC-Group/wv

cache:
  packages: true

notifications:
  slack: smac-group:xDmgBSAsmTP21Q2zj3LkUntt
